FactoryGirl.define do
  factory :health_plan do
    name "MyString"
region 1
carrier_id 1
age_20 1.5
age_21 1.5
age_22 1.5
age_23 1.5
age_24 1.5
age_25 1.5
age_26 1.5
age_27 1.5
age_28 1.5
age_29 1.5
age_30 1.5
age_31 1.5
age_32 1.5
age_33 1.5
age_34 1.5
age_35 1.5
age_36 1.5
age_37 1.5
age_38 1.5
age_39 1.5
age_40 1.5
age_41 1.5
age_42 1.5
age_43 1.5
age_44 1.5
age_45 1.5
age_46 1.5
age_47 1.5
age_48 1.5
age_49 1.5
age_50 1.5
age_51 1.5
age_52 1.5
age_53 1.5
age_54 1.5
age_55 1.5
age_56 1.5
age_57 1.5
age_58 1.5
age_59 1.5
age_60 1.5
age_61 1.5
age_62 1.5
age_63 1.5
age_64 1.5
age_65 1.5
metal_level "MyString"
plan_type "MyString"
office_visit_for_primary_doctor "MyString"
office_visit_for_specialist "MyString"
office_visit_for_other_practitioner "MyString"
annual_deductible_person 1
annual_deductible_family 1
coinsurance "MyString"
annual_out_of_pocket_limit "MyString"
lifetime_maximum 1
hsa_eligible "MyString"
out_of_network_coverage "MyString"
primary_care_physician_required "MyString"
specialist_referrals_required "MyString"
periodic_health_exam "MyString"
periodic_obgyn_exam "MyString"
well_baby_care "MyString"
retail_prescription_drugs "MyString"
separate_prescription_drug_deductible "MyString"
mail_order_prescription_drugs "MyString"
mail_order_supply "MyString"
outpatient_surgery "MyString"
outpatient_lab_xray "MyString"
imaging "MyString"
outpatient_mental_health "MyString"
outpatient_substance_abuse "MyString"
emergency_room "MyString"
emergency_ambulance_services "MyString"
urgent_care_facility "MyString"
hospitalization "MyString"
inpatient_mental_health "MyString"
inpatient_substance_abuse "MyString"
pre_postnatal_office_visit "MyString"
labor_delivery_hospital_stay "MyString"
dental_checkup_for_children "MyString"
vision_screening_for_children "MyString"
eye_glasses_for_children "MyString"
chiropractic_coverage "MyString"
major_dental_coverage "MyString"
vision_coverage "MyString"
plan_brochure_document_url "MyString"
summary_of_benefits_document_url "MyString"
carrier_name "MyString"
  end

end
