# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20150514055432) do

  create_table "health_plans", force: true do |t|
    t.string   "name"
    t.integer  "region"
    t.integer  "carrier_id"
    t.float    "age_20"
    t.float    "age_21"
    t.float    "age_22"
    t.float    "age_23"
    t.float    "age_24"
    t.float    "age_25"
    t.float    "age_26"
    t.float    "age_27"
    t.float    "age_28"
    t.float    "age_29"
    t.float    "age_30"
    t.float    "age_31"
    t.float    "age_32"
    t.float    "age_33"
    t.float    "age_34"
    t.float    "age_35"
    t.float    "age_36"
    t.float    "age_37"
    t.float    "age_38"
    t.float    "age_39"
    t.float    "age_40"
    t.float    "age_41"
    t.float    "age_42"
    t.float    "age_43"
    t.float    "age_44"
    t.float    "age_45"
    t.float    "age_46"
    t.float    "age_47"
    t.float    "age_48"
    t.float    "age_49"
    t.float    "age_50"
    t.float    "age_51"
    t.float    "age_52"
    t.float    "age_53"
    t.float    "age_54"
    t.float    "age_55"
    t.float    "age_56"
    t.float    "age_57"
    t.float    "age_58"
    t.float    "age_59"
    t.float    "age_60"
    t.float    "age_61"
    t.float    "age_62"
    t.float    "age_63"
    t.float    "age_64"
    t.float    "age_65"
    t.string   "metal_level"
    t.string   "plan_type"
    t.string   "office_visit_for_primary_doctor"
    t.string   "office_visit_for_specialist"
    t.string   "office_visit_for_other_practitioner"
    t.integer  "annual_deductible_person"
    t.integer  "annual_deductible_family"
    t.string   "coinsurance"
    t.string   "annual_out_of_pocket_limit"
    t.integer  "lifetime_maximum"
    t.string   "hsa_eligible"
    t.string   "out_of_network_coverage"
    t.string   "primary_care_physician_required"
    t.string   "specialist_referrals_required"
    t.string   "periodic_health_exam"
    t.string   "periodic_obgyn_exam"
    t.string   "well_baby_care"
    t.string   "retail_prescription_drugs"
    t.string   "separate_prescription_drug_deductible"
    t.string   "mail_order_prescription_drugs"
    t.string   "mail_order_supply"
    t.string   "outpatient_surgery"
    t.string   "outpatient_lab_xray"
    t.string   "imaging"
    t.string   "outpatient_mental_health"
    t.string   "outpatient_substance_abuse"
    t.string   "emergency_room"
    t.string   "emergency_ambulance_services"
    t.string   "urgent_care_facility"
    t.string   "hospitalization"
    t.string   "inpatient_mental_health"
    t.string   "inpatient_substance_abuse"
    t.string   "pre_postnatal_office_visit"
    t.string   "labor_delivery_hospital_stay"
    t.string   "dental_checkup_for_children"
    t.string   "vision_screening_for_children"
    t.string   "eye_glasses_for_children"
    t.string   "chiropractic_coverage"
    t.string   "major_dental_coverage"
    t.string   "vision_coverage"
    t.string   "plan_brochure_document_url"
    t.string   "summary_of_benefits_document_url"
    t.string   "carrier_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "zip_codes", force: true do |t|
    t.integer  "zipcode"
    t.integer  "aetna_health"
    t.integer  "aetna_vision"
    t.integer  "aetna_dental"
    t.integer  "aetna_life"
    t.integer  "anthem_health"
    t.integer  "anthem_vision"
    t.integer  "anthem_dental"
    t.integer  "anthem_life"
    t.integer  "blue_shield_health"
    t.integer  "blue_shield_vision"
    t.integer  "blue_shield_dental"
    t.integer  "blue_shield_life"
    t.integer  "health_net_health"
    t.integer  "health_net_vision"
    t.integer  "health_net_dental"
    t.integer  "health_net_life"
    t.integer  "kaiser_health"
    t.integer  "kaiser_vision"
    t.integer  "kaiser_dental"
    t.integer  "kaiser_life"
    t.integer  "united_health"
    t.integer  "united_vision"
    t.integer  "united_dental"
    t.integer  "united_life"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
