class CreateHealthPlans < ActiveRecord::Migration
  def change
    create_table :health_plans do |t|
      t.string :name
      t.integer :region
      t.integer :carrier_id
      t.float :age_20
      t.float :age_21
      t.float :age_22
      t.float :age_23
      t.float :age_24
      t.float :age_25
      t.float :age_26
      t.float :age_27
      t.float :age_28
      t.float :age_29
      t.float :age_30
      t.float :age_31
      t.float :age_32
      t.float :age_33
      t.float :age_34
      t.float :age_35
      t.float :age_36
      t.float :age_37
      t.float :age_38
      t.float :age_39
      t.float :age_40
      t.float :age_41
      t.float :age_42
      t.float :age_43
      t.float :age_44
      t.float :age_45
      t.float :age_46
      t.float :age_47
      t.float :age_48
      t.float :age_49
      t.float :age_50
      t.float :age_51
      t.float :age_52
      t.float :age_53
      t.float :age_54
      t.float :age_55
      t.float :age_56
      t.float :age_57
      t.float :age_58
      t.float :age_59
      t.float :age_60
      t.float :age_61
      t.float :age_62
      t.float :age_63
      t.float :age_64
      t.float :age_65
      t.string :metal_level
      t.string :plan_type
      t.string :office_visit_for_primary_doctor
      t.string :office_visit_for_specialist
      t.string :office_visit_for_other_practitioner
      t.integer :annual_deductible_person
      t.integer :annual_deductible_family
      t.string :coinsurance
      t.string :annual_out_of_pocket_limit
      t.integer :lifetime_maximum
      t.string :hsa_eligible
      t.string :out_of_network_coverage
      t.string :primary_care_physician_required
      t.string :specialist_referrals_required
      t.string :periodic_health_exam
      t.string :periodic_obgyn_exam
      t.string :well_baby_care
      t.string :retail_prescription_drugs
      t.string :separate_prescription_drug_deductible
      t.string :mail_order_prescription_drugs
      t.string :mail_order_supply
      t.string :outpatient_surgery
      t.string :outpatient_lab_xray
      t.string :imaging
      t.string :outpatient_mental_health
      t.string :outpatient_substance_abuse
      t.string :emergency_room
      t.string :emergency_ambulance_services
      t.string :urgent_care_facility
      t.string :hospitalization
      t.string :inpatient_mental_health
      t.string :inpatient_substance_abuse
      t.string :pre_postnatal_office_visit
      t.string :labor_delivery_hospital_stay
      t.string :dental_checkup_for_children
      t.string :vision_screening_for_children
      t.string :eye_glasses_for_children
      t.string :chiropractic_coverage
      t.string :major_dental_coverage
      t.string :vision_coverage
      t.string :plan_brochure_document_url
      t.string :summary_of_benefits_document_url
      t.string :carrier_name

      t.timestamps
    end
  end
end
